# Generated by Django 5.2.17 on 2026-10-07 23:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitiveTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('memory', 'Memory'), ('attention', 'Attention'), ('regularity', 'Regularity')], max_length=20)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_tests', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-taken_at'],
                'indexes': [models.Index(fields=['patient', 'taken_at'], name='cognitive_t_patient_cb404d_idx')],
            },
        ),
    ]
